import nlp.ArrayTokenized;
import nlp.Corpus;
import nlp.TokenizedHeading;
import nlp.TokenizedParagraph;
import nlp.languages.Farsi;
import nlp.ngram.CountTable;
import nlp.ngram.ProbabilityTable;
import web.html.HTMLDocument;
import web.html.HTMLUtilities;
import web.wikipedia.RandomDocumentGenerator;

public class NgramBigTest {
    public static void main(String[] args) {

        int n = 1;

        Corpus corpus = CorpusGeneratorTest.generateCorpus(new RandomDocumentGenerator(new Farsi()), 1);
        CountTable ct = corpus.getCountTable(n);
        ProbabilityTable pt = corpus.getProbabilityTable(n);

        HTMLDocument report = new HTMLDocument();
        report.add(HTMLUtilities.DEFAULT_STYLE);
        report.add(new TokenizedHeading(new ArrayTokenized("Report"), 5));

        report.add(new TokenizedHeading(new ArrayTokenized("Articles used in the corpus"), 2));
        report.add(HTMLUtilities.toList(corpus, false, CorpusGeneratorTest.DOCUMENT_TO_STRING));

        report.add(new TokenizedHeading(new ArrayTokenized("Count Table"), 2));
        report.add(HTMLUtilities.toTable(ct));

        report.add(new TokenizedHeading(new ArrayTokenized("Probability Table"), 2));
        report.add(HTMLUtilities.toTable(pt));

        report.add(new TokenizedHeading(new ArrayTokenized("Notes"), 2));
        report.add(new TokenizedParagraph(new ArrayTokenized("Generated by https://github.com/smm-h/nlp")));

        HTMLUtilities.show(report);
    }

}
