import nlp.ArrayTokenized;
import nlp.Corpus;
import nlp.Document;
import nlp.Utilities;
import nlp.HashCorpus;
import nlp.Term;
import nlp.TokenizedHeading;
import nlp.TokenizedParagraph;
import nlp.ngram.CountTable;
import nlp.ngram.ProbabilityTable;
import web.html.HTMLDocument;
import web.html.HTMLUtilities;

public class NgramSmallTest {
    public static void main(String[] args) {
        Document d1 = Utilities.getDocumentFromCharsAsTokens("acaa.");
        Document d2 = Utilities.getDocumentFromCharsAsTokens("abba.");
        Document d3 = Utilities.getDocumentFromCharsAsTokens("ccab.");
        Document d4 = Utilities.getDocumentFromCharsAsTokens("aacc.");
        Document d5 = Utilities.getDocumentFromCharsAsTokens("abac.");
        Corpus corpus = new HashCorpus(d1, d2, d3, d4, d5);

        int n = 1; // bi-gram <=> n = 1
        CountTable ct = corpus.getCountTable(n);
        ProbabilityTable pt = corpus.getProbabilityTable(n);

        Term term = Utilities.getTermFromCharsAsTokens("acc.");
        System.out.println("PRODUCT:");
        System.out.println("p(" + term + ") = " + pt.getProbabilityOf(term));
        System.out.println("\nSUM OF LOG:");
        System.out.println("p(" + term + ") = " + pt.getLogarithmicProbabilityOf(term));

        HTMLDocument report = new HTMLDocument();
        report.add(HTMLUtilities.DEFAULT_STYLE);
        report.add(new TokenizedHeading(new ArrayTokenized("Report"), 1));

        report.add(new TokenizedHeading(new ArrayTokenized("Count Table"), 2));
        report.add(HTMLUtilities.toTable(ct));

        report.add(new TokenizedHeading(new ArrayTokenized("Probability Table"), 2));
        report.add(HTMLUtilities.toTable(pt));

        report.add(new TokenizedHeading(new ArrayTokenized("Notes"), 2));
        report.add(new TokenizedParagraph(new ArrayTokenized("Generated by https://github.com/smm-h/nlp")));

        HTMLUtilities.show(report);
    }

}
