import java.nio.file.Files;
import java.nio.file.Path;

import nlp.ArrayTokenized;
import nlp.Corpus;
import nlp.Utilities;
import nlp.HashCorpus;
import nlp.TokenizedHeading;
import nlp.TokenizedParagraph;
import nlp.ngram.CountTable;
import nlp.ngram.ProbabilityTable;
import web.html.HTMLDocument;
import web.html.HTMLUtilities;

// @SuppressWarnings("unused")
public class NgramBiggerTest {
    public static void main(String[] args) throws Exception {

        int n = 1;

        Corpus corpus = new HashCorpus();

        Path p = Path.of("res/ctpr/n-gram-corpus-data.txt");

        // for (String i : Common.over(Files.lines(p).iterator())) {

        for (String line : Files.readAllLines(p)) {
            corpus.add(Utilities.getDocumentFromCharsAsTokens(line));
        }

        CountTable ct = corpus.getCountTable(n);
        ProbabilityTable pt = corpus.getProbabilityTable(n);

        HTMLDocument report = new HTMLDocument();
        report.add(HTMLUtilities.DEFAULT_STYLE);
        report.add(new TokenizedHeading(new ArrayTokenized("Report"), 1));

        report.add(new TokenizedHeading(new ArrayTokenized("Count Table"), 2));
        report.add(HTMLUtilities.toTable(ct));

        report.add(new TokenizedHeading(new ArrayTokenized("Probability Table"), 2));
        report.add(HTMLUtilities.toTable(pt));

        report.add(new TokenizedHeading(new ArrayTokenized("Notes"), 2));
        report.add(new TokenizedParagraph(new ArrayTokenized("Generated by https://github.com/smm-h/nlp")));

        HTMLUtilities.show(report);
    }

}
